apiVersion: v1
name: efs-chart
description: A Helm chart for the ACK service controller for Amazon Elastic File System (EFS)
version: 1.0.6
appVersion: 1.0.6
home: https://github.com/aws-controllers-k8s/efs-controller
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - https://github.com/aws-controllers-k8s/efs-controller
maintainers:
  - name: ACK Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/ack-admin
  - name: EFS Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/efs-maintainer
keywords:
  - aws
  - kubernetes
  - efs
